/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/error_assistant/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain an error
         * @description Asks the configured AI provider to explain an error and suggest a fix.
         */
        post: operations["explainError"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/error_assistant/no_match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Route an unresolved error
         * @description Use this when search did not find a useful internal match. The backend
         *     classifies the error and returns the best Slack channel plus a draft message
         *     asking for help.
         */
        post: operations["routeNoMatchError"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/error_assistant/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search internal debugging context
         * @description Searches enabled internal sources, usually Slack and optionally Notion, for
         *     related debugging context, merges the results, scores them, and summarizes
         *     strong matches.
         */
        post: operations["searchErrorContext"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/error_assistant/weak_match": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Classify low-confidence matches
         * @description Use this when search results exist but are below the configured confidence
         *     threshold. The backend labels weak results as low confidence and generates a
         *     short note explaining why they are loose matches.
         */
        post: operations["classifyWeakMatches"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/up": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Returns a simple status payload when the Rails app is running.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        BaseSearchResult: {
            source: components["schemas"]["SearchSource"];
            text: string;
            /** Format: uri */
            permalink?: string | null;
            source_links: string[];
            /** Format: double */
            score: number;
            score_breakdown: string;
            /** @description Summary, present only when result summarization runs for a strong match. */
            summary?: string;
        };
        ErrorResponse: {
            error: string;
        };
        /** @enum {string} */
        ErrorType: "database" | "authentication" | "nil_reference" | "network" | "test_failure" | "default";
        ExplainRequest: {
            /** @description Error message, exception, or stack trace. */
            error: string;
            /** @description Relevant code snippet. */
            code?: string;
            /** @description Language for the code snippet. */
            language?: string;
        };
        ExplainResponse: {
            explanation: string;
            /** @description Null when the provider returns unparseable non-JSON text. */
            suggested_fix: string | null;
        };
        ExtractedKeywords: {
            /** @description Exception class extracted from the error, when present. */
            exception_class?: string | null;
            /** @description Method name extracted from the error, when present. */
            method_name?: string | null;
            domain_keywords: string[];
        };
        HealthResponse: {
            /** @enum {string} */
            status: "ok";
        };
        /** @enum {string} */
        MatchStatus: "strong_match" | "weak_match" | "no_match";
        NoMatchRequest: {
            /** @description Error message, exception, or stack trace. */
            error: string;
            /** @description Relevant code snippet. */
            code?: string;
            /** @description Language for the code snippet. */
            language?: string;
        };
        NoMatchResponse: {
            error_type: components["schemas"]["ErrorType"];
            channel_name: string | null;
            /** Format: uri */
            channel_permalink: string | null;
            draft_message: string;
        };
        NotionSearchResult: {
            /** @enum {string} */
            source: "notion";
            title?: string;
            /** @description Notion last edited timestamp. */
            ts?: string;
        } & WithRequired<components["schemas"]["BaseSearchResult"], "source">;
        SearchRequest: {
            /** @description Error message, exception, or stack trace to search for. */
            error: string;
            /** @description Extra search context, such as domain, service, team, or library name. */
            context?: string;
            /** @description Set to false to skip per-result summaries for this request, even on strong matches. */
            summarize?: boolean;
        };
        SearchResponse: {
            /** @description Core error text after summarisation/noise removal. */
            core_error: string;
            /** @description Final extracted search query used against enabled internal sources. */
            query: string;
            extracted_keywords: components["schemas"]["ExtractedKeywords"];
            /** @description Backend confidence classification for the merged search results. */
            match_status: components["schemas"]["MatchStatus"];
            /**
             * Format: double
             * @description Score threshold used to distinguish weak and strong matches.
             */
            weak_match_threshold: number;
            /** @description Up to 20 merged Slack and Notion results, sorted by score descending. */
            results: components["schemas"]["SearchResult"][];
            /** @description Frequently repeated keywords from the top results. */
            common_keywords: string[];
        };
        SearchResult: components["schemas"]["SlackSearchResult"] | components["schemas"]["NotionSearchResult"];
        /** @enum {string} */
        SearchSource: "slack" | "notion";
        SlackReaction: {
            name?: string;
            /** Format: int32 */
            count?: number;
        };
        SlackSearchResult: {
            /** @enum {string} */
            source: "slack";
            channel_name?: string | null;
            channel_id?: string | null;
            /** @description Slack timestamp string. */
            ts?: string;
            reactions?: components["schemas"]["SlackReaction"][];
            /** Format: int32 */
            reply_count?: number;
        } & WithRequired<components["schemas"]["BaseSearchResult"], "source">;
        WeakMatchInputResult: {
            source?: string;
            text?: string;
            /** Format: double */
            score?: number;
            /** Format: uri */
            permalink?: string;
        };
        WeakMatchRequest: {
            /** @description Error message, exception, or stack trace. */
            error: string;
            /** @description Search results to evaluate. Omitted or invalid values are treated as an empty array by the backend. */
            results?: components["schemas"]["WeakMatchInputResult"][];
        };
        WeakMatchResponse: {
            /** @enum {string} */
            confidence: "low";
            /**
             * Format: double
             * @description Configured weak-match threshold.
             */
            threshold: number;
            note: string;
            results: components["schemas"]["WeakMatchResult"][];
        };
        WeakMatchResult: {
            /** @enum {string} */
            confidence: "low";
        } & components["schemas"]["WeakMatchInputResult"];
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    explainError: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    routeNoMatchError: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NoMatchRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NoMatchResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    searchErrorContext: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    classifyWeakMatches: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WeakMatchRequest"];
            };
        };
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WeakMatchResponse"];
                };
            };
            /** @description Access is unauthorized. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Client error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The request has succeeded. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
type WithRequired<T, K extends keyof T> = T & {
    [P in K]-?: T[P];
};
